### ISSUE TITLE
authentication against HA controllers requires login to each IP address

### ISSUE THREAD

**Issue by jameinel** [CanonicalLtd/candid#109]
See bug reported:
https://bugs.launchpad.net/bugs/1804401

My guess is that if you are using controllers without a DNS name, we end up with a list of IP addresses to connect to, and the macaroon for the cluster is stored per-IP rather than allowing a list of IPs that all have the same macaroon.

It is possible that it is an issue with how Juju is using the library, but it would be good to get clarity on how it should be done to allow sharing the macaroon cache across several IP addresses.

**Comment by mhilton** [comment]
This is not a candid issue. discharged macaroons are not tied to a single address.
