### ISSUE TITLE
Problem with LDAP authentication and user-query-filter

### ISSUE THREAD

**Issue by mattsjakobsson** [CanonicalLtd/candid#112]
When using ldap if user-query-filter does not return a user the we get an error PANIC!: runtime error: index out of range since we seem to assume that the user-query-filter always get a match.

Authentication succeeds if we are both allow to bind to ldap (AD) with the credentials and also if user-query-filter returns an object.
This way we can limit access to certain ldap groups with user-query-filter 

Nov 22 09:13:07 juju-64829d-0-lxd-0 candid.candidsrv[5875]: 2018-11-22 09:13:07 DEBUG candid.internal.discharger api.go:106 opForRequest &discharger.legacyLoginRequest{Route:httprequest.Route{},
Domain:"", DischargeID:"003ec7a307f6fedf1b10831d6b557b02615868f58bccb0ce5dd730bd336e36fd"} -> bakery.Op{Entity:"global", Action:"login"}
Nov 22 09:13:07 juju-64829d-0-lxd-0 candid.candidsrv[5875]: 2018-11-22 09:13:07 DEBUG bakery logger.go:28 operations still needed after auth check: []bakery.Op{bakery.Op{Entity:"login", Action:"l
ogin"}}
Nov 22 09:13:07 juju-64829d-0-lxd-0 candid.candidsrv[5875]: 2018-11-22 09:13:07 INFO bakery.identchecker logger.go:33 allow loginop: (*bakery.AuthInfo)(nil); err [{/root/go/pkg/mod/gopkg.in/macar
oon-bakery.v2@v2.1.0/bakery/checker.go:343: permission denied}]
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: 2018-11-22 09:13:17 ERROR candid.internal.identity server.go:169 PANIC!: runtime error: index out of range
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: goroutine 23 [running]:
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: runtime/debug.Stack(0xc0004915d8, 0xaf8580, 0x1169250)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/snap/go/3039/src/runtime/debug/stack.go:24 +0xa7
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/internal/identity.(*Server).ServeHTTP.func1(0x7fb90b0cb1e0, 0xc000154f90)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/internal/identity/server.go:169 +0x6e
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: panic(0xaf8580, 0x1169250)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/snap/go/3039/src/runtime/panic.go:513 +0x1b9
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/idp/ldap.(*identityProvider).loginDN(0xc000260300, 0xc9ba80, 0xc000154fc0, 0xc9be80, 0xc0001a55f0, 0xc00
0026540, 0x54, 0xc0001e22f0, 0xe, 0x1, ...)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/idp/ldap/ldap.go:324 +0x87c
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/idp/ldap.(*identityProvider).loginUser(0xc000260300, 0xc9ba80, 0xc000154fc0, 0xc0003a8129, 0x6, 0xc0001e
22f0, 0xe, 0x0, 0x0, 0x0)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/idp/ldap/ldap.go:304 +0x18b
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/idp/ldap.(*identityProvider).handleLogin(0xc000260300, 0xc9ba80, 0xc000154fc0, 0x7fb90b0cb1e0, 0xc000154
f90, 0xc0003ae100, 0xc000155080, 0x0)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/idp/ldap/ldap.go:284 +0xd2
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/idp/ldap.(*identityProvider).Handle(0xc000260300, 0xc9ba80, 0xc000154fc0, 0x7fb90b0cb1e0, 0xc000154f90,
0xc0003ae100)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/idp/ldap/ldap.go:271 +0xe3
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/internal/discharger.newIDPHandler.func1(0x7fb90b0cb1e0, 0xc000154f90, 0xc0003ae100, 0xc0001d7200, 0x1, 0
x1)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/internal/discharger/idp.go:73 +0x2cc
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0002c4400, 0x7fb90b0cb1e0, 0xc000154f90, 0xc0003ae100)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/root/go/pkg/mod/github.com/julienschmidt/httprouter@v0.0.0-20151013225520-77a895ad01eb/router.go:299 +0x6cf
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/CanonicalLtd/candid/internal/identity.(*Server).ServeHTTP(0xc0002a3460, 0x7fb90b0cb1e0, 0xc000154f90, 0xc0003ae100)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/build/candid/parts/candid/build/internal/identity/server.go:179 +0x168
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xc93b80, 0xc0002c8de0, 0x7fb90b0cb160, 0xc0002a3460, 0xc9a880, 0xc00039a1c0, 0xc0003ae100)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/root/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20170224193955-13d73096a474/handlers.go:77 +0x22f
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: net/http.serverHandler.ServeHTTP(0xc000326410, 0xc9a880, 0xc00039a1c0, 0xc0003ae100)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/snap/go/3039/src/net/http/server.go:2741 +0xab
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: net/http.(*conn).serve(0xc0003ac140, 0xc9b9c0, 0xc0003f4340)
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/snap/go/3039/src/net/http/server.go:1847 +0x646
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: created by net/http.(*Server).Serve
Nov 22 09:13:17 juju-64829d-0-lxd-0 candid.candidsrv[5875]: #011/snap/go/3039/src/net/http/server.go:2851 +0x2f5
Nov 22 09:14:07 juju-64829d-0-lxd-0 candid.candidsrv[5875]: 2018-11-22 09:14:07 ERROR candid.internal.identity json.go:53 Internal Server Error: cannot wait: cannot wait: rendezvous wait timed out ([{/build/candid/parts/candid/build/internal/discharger/wait.go:86: } {/build/candid/parts/candid/build/internal/discharger/wait.go:139: cannot wait} {/build/candid/parts/candid/build/internal/discharger/meeting.go:57: cannot wait} {/build/candid/parts/candid/build/meeting/meeting.go:309: rendezvous wait timed out}])

**Comment by mhilton** [comment]
This is now fixed

**Comment by mattsjakobsson** [comment]
Woks like a charm, thank you very much

**Comment by mattsjakobsson** [comment]
Works great, thank you very much
