### ISSUE TITLE
Add domain prompt page

### ISSUE THREAD

**Issue by stgraber** [CanonicalLtd/candid#113]
Currently when logging in with Candid and you don't specify &domain=blah in the URL, Candid just picks an identity provider for you with no way for the user to actually select the one that makes sense for them.

For LXD, we have support in our client for specifying the domain, so we get around that issue.
But it's now a problem when working on the RBAC web UI as it just redirects you to Candid with no way to edit the URL to append the domain, then Candid immediately bounces you to Ubuntu SSO, never giving you a chance to change domain.

The best user experience in my opinion would be for Candid to detect cases where no domain was specified in the URL and more than one identity provider is defined in the config.
In such cases, a list of domains should be shown to the user, clicking on whichever they want would then send them to authenticate using that domain.

That would make handling multi-domain environments for web services using Candid, much much easier.

**Comment by albertodonato** [comment]
Maybe we could add an option to the client liberaries so that the URL returned to the browser interactor has the `&domain=blah` option added, without the need to hack it frrom the code using it.

Still, in case multiple domains are configured and one is not specified (or an invalid one is passed), Candid should prompt the user somehow

**Comment by rogpeppe** [comment]
Yes, we intend to fix this sooner rather than later.

**Comment by mattsjakobsson** [comment]
+1
We would really like to use candid as identity manager connected with several different IdP for use with juju  controllers

**Comment by clagom** [comment]
Hello, we briefly discussed this during Cape Town, when we talked about the Candid homepage. You can see an initial exploration here: https://scene.zeplin.io/project/5c6c07246f0f43465e1e387b
Please let me know your comment, thanks @stgraber

**Comment by stgraber** [comment]
@clagom so the issue with a login page like this one is that not all domains will use user/password authentication.

Say I have my candid setup with:
 - Local authentication
 - LDAP authentication
 - Ubuntu SSO
 - Google SSO

Only the first two do user/password authentication, the other two domains will instead redirect the user directly to an external website.

In my head I always saw this as a two step method:

 - Confirm request and choose domain. If you have more than one domain enabled, this page would show a list of domains and icons (if present) and let the user click on whichever they want. If there is a single domain, this page should just indicate that something wants to authenticate with Candid and require the user to click a button to go through with the request. This page must always be shown to prevent automated attacks against Candid (we require some kind of user interaction).

 - If the domain selected requires a user and password, as is the case with the local or ldap case, then ask for that information now. Depending on domains, this page may also be asking for additional information like a 2FA token (not currently done by any of the authentication mechanisms that use this page, but it's plausible that we'd need to add this later on).

**Comment by clagom** [comment]
Thank you @stgraber for the information, I see what you mean. I'll update the proposal accordingly.

**Comment by clagom** [comment]
I updated the screens @stgraber:
(also on Zeplin: https://scene.zeplin.io/project/5c6c07246f0f43465e1e387b)

Single domain:
![Candid log-in single 01](https://user-images.githubusercontent.com/1953388/55154190-17319300-514c-11e9-85d8-1e1d1bc93ece.png)

Multi-domain list:
![Candid log-in multi 01](https://user-images.githubusercontent.com/1953388/55154211-21ec2800-514c-11e9-8e1d-a2b2f6a44774.png)

Choose one:
![Candid log-in multi 01b](https://user-images.githubusercontent.com/1953388/55154235-2d3f5380-514c-11e9-8b94-6d8b66f19095.png)

Login
![Candid log-in multi 02](https://user-images.githubusercontent.com/1953388/55154285-4cd67c00-514c-11e9-8c62-e761e57fe44e.png)

2FA:
![Candid log-in multi 02 2FA](https://user-images.githubusercontent.com/1953388/55154291-53fd8a00-514c-11e9-9417-19b211a942d1.png)

**Comment by stgraber** [comment]
Looks good to me!

**Comment by anthonydillon** [comment]
@mhilton can we say this is complete with the latest PRs?

**Comment by anthonydillon** [comment]
These views have been implemented will be available in the next release.

**Comment by mhilton** [comment]
This is done now
