### ISSUE TITLE
Configuration not perstent acress refresh

### ISSUE THREAD

**Issue by mattsjakobsson** [CanonicalLtd/candid#122]
Commit https://github.com/CanonicalLtd/candid/commit/a91b0d8e13dedb1c2e77035d6da1a283a571e5da
Seems to have the effect that each refresh will create a default configuration file and thus configuration is not persistent across updates/refresh as when the config was stored in common.

**Comment by albertodonato** [comment]
HI Matts,

this was a one-time breakage as the path where config is stored was changed.
You should be able to fix it as follows:

```
sudo mv /var/snap/candid/common/{admin.keys,config.yaml} /var/snap/candid/current
sudo snap restart candid
```

Configs are now kept in `$SNAP_DATA` which is per-revision, but snapd will take care of copying everything over on updates.

Also, note that if you're currently installing the snap frrom the `edge` channel, you might want to switch to the `stable` one, as edge contains master builds:

```
sudo snap refresh --stable candid
```

Please let me know if the above fixes your issue.

**Comment by mattsjakobsson** [comment]
Hi
Ahh that makes much more sense.
"but snapd will take care of copying everything over on updates"
Was the piece I was missing. Lack of knowledge on my part.

Yes installing from stable would make more sense when moving into production.

Thank you
