### ISSUE TITLE
The login page need domain context

### ISSUE THREAD

**Issue by anthonydillon** [CanonicalLtd/candid#143]
For the latest designs we would like to display the selected identity provider. The view needs to be sent the identity provider context so the template can use the details to render the correct information.

![Screenshot_2019-06-20 Zeplin - Project](https://user-images.githubusercontent.com/1413534/59838886-a8796580-9347-11e9-93e8-1130a8328570.png)

**Comment by mhilton** [comment]
This is fixed in #146
