### ISSUE TITLE
Prettify error messages returned by Candid in MAAS

### ISSUE THREAD

**Issue by exceptorr** [CanonicalLtd/candid#158]
![image](https://user-images.githubusercontent.com/2902448/62795276-18ea6a80-badf-11e9-958e-06ad92ec617b.png)

Steps to reproduce:

1) You should have two users in your identity backend with same email addresses. Candid config.yaml example on which this could be reproduced: http://paste.ubuntu.com/p/Y4RV6XWhZD/
2) Login with first user (admin1) - it will let you log in, no problems so far
3) Logout, login with second user (admin2) - an error like in screenshot will be shown.

**Comment by mhilton** [comment]
This error is not from candid, this looks like it's a MAAS error.
