### ISSUE TITLE
Candid should raise an error if key in user schema is missing

### ISSUE THREAD

**Issue by exceptorr** [CanonicalLtd/candid#159]
Currently, Candid is creating a user in MAAS with empty value in "email" field instead of raising some error (that behaviour led me to discovery of https://github.com/CanonicalLtd/candid/issues/158 issue).

Steps to reproduce:

1) Configure Candid using this config file: http://paste.ubuntu.com/p/Bp6PkG8VHf/ (note, "admin2" user doesn't have any email address specified in his definition). 
2) Try to login with that user. MAAS will let you in, but "email" field would be empty:
![image](https://user-images.githubusercontent.com/2902448/62795865-5f8c9480-bae0-11e9-815d-558bb25b05ba.png)

Moreover:
3) Modify Candid config.yaml using this one: http://paste.ubuntu.com/p/K7q9b7wsxg/
4) Try to login with admin3
5) You will hit https://github.com/CanonicalLtd/candid/issues/158 issue.

**Comment by mhilton** [comment]
It is not a problem for candid if a user doesn't have an email address. Some supported identity providers do not include an email address, so this shouldn't be changed in general.

@urosj what, if anything, should we do with this bug?

**Comment by exceptorr** [comment]
> It is not a problem for candid if a user doesn't have an email address

Indeed, but maybe we should, at least, raise some warning if Candid is configured to get key/values from identity provider, but there is no corresponding key in user schema returned by IdP?

**Comment by mhilton** [comment]
Candid considers the email address an optional value. Any client that requires an email address should handle that itself.
