### ISSUE TITLE
Candid allows a malicious user to detect valid usernames 

### ISSUE THREAD

**Issue by CalvinHartwell** [CanonicalLtd/candid#160]
Hi all, 

One of our customers has flagged that Candid can be used to detect "valid usernames" in order to gather information for a brute-force attack. 

There are four potential scenarios when a user attempts to login: 
1. Valid Username and Valid Password
2. Invalid Username and Invalid Password
3. Valid Username and Invalid Password
4. Invalid Username and Valid Password. 

Scenario (1) will authenticate us, Scenario (2) will produce an invalid credentials error similar to (4). 

However, the main problem exists with Scenario (3): the error which is given to the user when they attempt to login with a valid username but invalid username is different to when they attempt (2) and (4), and thus, it can be used to detect valid login names. 

The error which is shown for (3) is as follows: 

"Error: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DIS-0C09042F, comment: AcceptSecurityContext error,data 52e, v2580"

A malicious user could use this mechanism to draw up a full list of valid usernames for a wider brute force attack. We may also want to introduce an anti-bruteforce (like captcha or timeout) mechanisms to further deter an attacker. 

Cheers,

- Calvin

**Comment by mhilton** [comment]
This was fixed by #161
