### ISSUE TITLE
Log in message is not aligned correctly

### ISSUE THREAD

**Issue by frankban** [CanonicalLtd/candid#39]
Moved from https://github.com/juju/juju-gui/issues/3378
See screenshot there

**Comment by barrymcgee** [comment]
<img width="824" alt="33717251-23519cce-db51-11e7-814f-ae75e5ca5a66" src="https://user-images.githubusercontent.com/505570/43400205-01a0a972-9405-11e8-9b81-cef9eb4011f5.png">
